[package]
name = "tikv-client-store"
version = "0.0.0"
edition = "2018"


[dependencies]
futures = { version = "0.3.5", features = ["compat", "async-await", "thread-pool"] }
kvproto = { git = "https://github.com/longfangsong/kvproto.git", features = [ "prost-codec" ], default-features = false }
derive-new = "0.5"
grpcio = { git = "https://github.com/tikv/grpc-rs.git", features = [ "secure", "prost-codec" ], default-features = false }
log = "0.4"

tikv-client-common = { path = "../tikv-client-common" }
