[package]
name = "tikv-client-store"
version = "0.0.0"
edition = "2018"

[dependencies]
async-trait = "0.1"
derive-new = "0.5"
futures = { version = "0.3.5", features = ["compat", "async-await", "thread-pool"] }
grpcio = { version = "0.7", features = ["secure", "prost-codec"], default-features = false }
log = "0.4"
tikv-client-common = { path = "../tikv-client-common" }
tikv-client-proto = { path = "../tikv-client-proto" }
