[package]
name = "tikv-client-pd"
version = "0.0.0"
edition = "2018"

[dependencies]
async-trait = "0.1"
futures = { version = "0.3.5", features = ["compat", "async-await", "thread-pool"] }
grpcio = { version = "0.8", features = [ "secure", "prost-codec", "use-bindgen" ], default-features = false }
log = "0.4"
tikv-client-common = { path = "../tikv-client-common" }
tikv-client-proto = { path = "../tikv-client-proto" }

[dev-dependencies]
clap = "2.32"
fail = { version = "0.4", features = [ "failpoints" ] }
proptest = "0.10"
proptest-derive = "0.2"
