[coprocessor]
region-max-keys = 10
region-split-keys = 7
batch-split-limit = 100

[raftstore]
region-split-check-diff = "0KB"
pd-heartbeat-tick-interval = "2s"
pd-store-heartbeat-tick-interval = "5s"
split-region-check-tick-interval = "1s"